name: EAS Build Android APK

on:
  push:
    branches:
      - main
  # Memungkinkan workflow dijalankan secara manual dari tab Actions di GitHub
  workflow_dispatch: 

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build on EAS
        run: eas build --platform android --profile preview --non-interactive
